### ISSUE TITLE
TypeError: Can't add property promiseLibrary, object is not extensible

### ISSUE THREAD

**Issue by kaytrance** [trailsjs/generator-trailpack#10]
I am trying to make a custom ORM trailpack by following 'trailpack-mongoose' repo. 
I have defined stores as stated [in documentation](https://github.com/trailsjs/trailpack-mongoose#configure-stores) but upon launching trails app on the following piece of code I get that TypeError.

```
// Setup promise library for mongoose
if (!store.options.promiseLibrary)
    store.promiseLibrary = global.Promise; // <-- error here
```

Why is that?

Here's my `database.js` part:

```
stores: {
   somedb: {
     uri: "test",
     migrate: "create",
     options: {
     }
   }
},

models: {
  defaultStore: 'somedb',
  migrate: 'drop'
}
```

**Comment by jaumard** [comment]
Now Trails freeze all `app.config` object for security reason, so it's a bug under `trailpack-mongoose` (please open an issue on the repo with the full error logs). Now all modification of `app.config` have to be done in `configure()` or you have to clone your config object under `initialize()` in order to modify it.

**Comment by jaumard** [comment]
I think all is good now :) feel free to reopen if it's not the case.
